# Daily GitHub Updates - NEARWEEK Format
name: Daily GitHub Updates

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 10:00 CET (9:00 UTC)
  workflow_dispatch:

jobs:
  github-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Fetch GitHub Updates
      env:
        GITHUB_TOKEN: ${{ secrets.DEV_TOKEN_GIT }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
      run: |
        echo "🔄 Fetching latest GitHub updates..."
        
        # Execute GitHub updates script with NEARWEEK format
        node src/scripts/github-updates.js --format=nearweek --post
        
    - name: Create execution summary
      run: |
        echo "## 📊 GitHub Updates Posted" >> $GITHUB_STEP_SUMMARY
        echo "**Execution Time**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "**Status**: ✅ Completed" >> $GITHUB_STEP_SUMMARY
        echo "**Format**: NEARWEEK Developer Focus" >> $GITHUB_STEP_SUMMARY
